export enum Permission {
  // Tours Management
  TOUR_VIEW = 'TOUR_VIEW',
  TOUR_CREATE = 'TOUR_CREATE',
  TOUR_EDIT = 'TOUR_EDIT',
  TOUR_DEACTIVATED = 'TOUR_DEACTIVATED',
  TOUR_ACTIVATED = 'TOUR_ACTIVATED',
  TOUR_APPROVED = 'TOUR_APPROVED',

  // Bookings Management
  BOOKING_VIEW = 'BOOKING_VIEW',
  BOOKING_CREATE = 'BOOKING_CREATE',
  BOOKING_EDIT = 'BOOKING_EDIT',
  BOOKING_DEACTIVATED = 'BOOKING_DEACTIVATED',
  BOOKING_ACTIVATED = 'BOOKING_ACTIVATED',
  BOOKING_CONFIRM = 'BOOKING_CONFIRM',
  BOOKING_CANCEL = 'BOOKING_CANCEL',
  BOOKING_COMPLETED = 'BOOKING_COMPLETED',

  // Payments Management
  PAYMENT_VIEW = 'PAYMENT_VIEW',
  PAYMENT_PROCESS = 'PAYMENT_PROCESS',
  PAYMENT_REFUND = 'PAYMENT_REFUND',

  // Reviews Management
  REVIEW_VIEW = 'REVIEW_VIEW',
  REVIEW_MODERATE = 'REVIEW_MODERATE',
  REVIEW_APPROVED = 'REVIEW_APPROVED',
  REVIEW_REJECTED = 'REVIEW_REJECTED',
  REVIEW_RESPONDED = 'REVIEW_RESPONDED',
  REVIEW_DEACTIVATED = 'REVIEW_DEACTIVATED',

  // Customers Management
  CUSTOMER_VIEW = 'CUSTOMER_VIEW',
  CUSTOMER_CREATE = 'CUSTOMER_CREATE',
  CUSTOMER_EDIT = 'CUSTOMER_EDIT',
  CUSTOMER_DEACTIVATED = 'CUSTOMER_DEACTIVATED',
  CUSTOMER_ACTIVATED = 'CUSTOMER_ACTIVATED',

  // Roles Management
  ROLE_VIEW = 'ROLE_VIEW',
  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_EDIT = 'ROLE_EDIT',
  ROLE_DEACTIVATED = 'ROLE_DEACTIVATED',
  ROLE_ACTIVATED = 'ROLE_ACTIVATED',
  ROLE_ASSIGN = 'ROLE_ASSIGN',

  // Vouchers Management
  VOUCHER_VIEW = 'VOUCHER_VIEW',
  VOUCHER_CREATE = 'VOUCHER_CREATE',
  VOUCHER_EDIT = 'VOUCHER_EDIT',
  VOUCHER_DEACTIVATED = 'VOUCHER_DEACTIVATED',
  VOUCHER_ACTIVATED = 'VOUCHER_ACTIVATED',
  VOUCHER_ASSIGN = 'VOUCHER_ASSIGN',

  // Destinations Management
  DESTINATION_VIEW = 'DESTINATION_VIEW',
  DESTINATION_CREATE = 'DESTINATION_CREATE',
  DESTINATION_EDIT = 'DESTINATION_EDIT',
  DESTINATION_DEACTIVATED = 'DESTINATION_DEACTIVATED',
  DESTINATION_ACTIVATED = 'DESTINATION_ACTIVATED',

  // Blogs Management
  BLOG_VIEW = 'BLOG_VIEW',
  BLOG_CREATE = 'BLOG_CREATE',
  BLOG_EDIT = 'BLOG_EDIT',
  BLOG_DEACTIVATED = 'BLOG_DEACTIVATED',
  BLOG_ACTIVATED = 'BLOG_ACTIVATED',
  BLOG_PUBLISH = 'BLOG_PUBLISH',
  BLOG_COMMENT_MODERATE = 'BLOG_COMMENT_MODERATE',

  // Notifications
  NOTIFICATION_VIEW = 'NOTIFICATION_VIEW',
  NOTIFICATION_SEND = 'NOTIFICATION_SEND',
  NOTIFICATION_DELETE = 'NOTIFICATION_DELETE',

  // Reports
  REPORT_VIEW = 'REPORT_VIEW',
  REPORT_EXPORT = 'REPORT_EXPORT',

  // Settings
  SETTING_VIEW = 'SETTING_VIEW',
  SETTING_UPDATE = 'SETTING_UPDATE',
}

// Nhóm permissions theo chức năng
export const PermissionGroups = {
  TOUR: [
    Permission.TOUR_VIEW,
    Permission.TOUR_CREATE,
    Permission.TOUR_EDIT,
    Permission.TOUR_DEACTIVATED,
    Permission.TOUR_ACTIVATED,
    Permission.TOUR_APPROVED,
  ],
  BOOKING: [
    Permission.BOOKING_VIEW,
    Permission.BOOKING_CREATE,
    Permission.BOOKING_EDIT,
    Permission.BOOKING_DEACTIVATED,
    Permission.BOOKING_ACTIVATED,
    Permission.BOOKING_CONFIRM,
    Permission.BOOKING_CANCEL,
    Permission.BOOKING_COMPLETED,
  ],
  PAYMENT: [
    Permission.PAYMENT_VIEW,
    Permission.PAYMENT_PROCESS,
    Permission.PAYMENT_REFUND,
  ],
  REVIEW: [
    Permission.REVIEW_VIEW,
    Permission.REVIEW_MODERATE,
    Permission.REVIEW_APPROVED,
    Permission.REVIEW_REJECTED,
    Permission.REVIEW_RESPONDED,
    Permission.REVIEW_DEACTIVATED,
  ],
  CUSTOMER: [
    Permission.CUSTOMER_VIEW,
    Permission.CUSTOMER_CREATE,
    Permission.CUSTOMER_EDIT,
    Permission.CUSTOMER_DEACTIVATED,
    Permission.CUSTOMER_ACTIVATED,
  ],

  ROLE: [
    Permission.ROLE_VIEW,
    Permission.ROLE_CREATE,
    Permission.ROLE_EDIT,
    Permission.ROLE_DEACTIVATED,
    Permission.ROLE_ACTIVATED,
    Permission.ROLE_ASSIGN,
  ],
  VOUCHER: [
    Permission.VOUCHER_VIEW,
    Permission.VOUCHER_CREATE,
    Permission.VOUCHER_EDIT,
    Permission.VOUCHER_DEACTIVATED,
    Permission.VOUCHER_ACTIVATED,
    Permission.VOUCHER_ASSIGN,
  ],
  DESTINATION: [
    Permission.DESTINATION_VIEW,
    Permission.DESTINATION_CREATE,
    Permission.DESTINATION_EDIT,
    Permission.DESTINATION_DEACTIVATED,
    Permission.DESTINATION_ACTIVATED,
  ],
  BLOG: [
    Permission.BLOG_VIEW,
    Permission.BLOG_CREATE,
    Permission.BLOG_EDIT,
    Permission.BLOG_DEACTIVATED,
    Permission.BLOG_ACTIVATED,
    Permission.BLOG_PUBLISH,
    Permission.BLOG_COMMENT_MODERATE,
  ],
  NOTIFICATION: [
    Permission.NOTIFICATION_VIEW,
    Permission.NOTIFICATION_SEND,
    Permission.NOTIFICATION_DELETE,
  ],
  REPORT: [Permission.REPORT_VIEW, Permission.REPORT_EXPORT],
  SETTING: [Permission.SETTING_VIEW, Permission.SETTING_UPDATE],
};
