import { MigrationInterface, QueryRunner } from "typeorm";

export class ChangeDatabase1765386683688 implements MigrationInterface {
    name = 'ChangeDatabase1765386683688'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "branch" RENAME COLUMN "lstPartMasterId" TO "isHeadquarters"`);
        await queryRunner.query(`CREATE TABLE "employee_certificate" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(36) NOT NULL, "updatedAt" TIMESTAMP DEFAULT now(), "updatedBy" character varying(36), "isDeleted" boolean NOT NULL DEFAULT false, "name" character varying NOT NULL, "code" character varying, "issueDate" TIMESTAMP WITH TIME ZONE, "expiryDate" TIMESTAMP WITH TIME ZONE, "issuingOrganization" character varying, "employeeId" uuid, CONSTRAINT "PK_dd07ae8d5737f841aaa2a4cf965" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "employee_education" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(36) NOT NULL, "updatedAt" TIMESTAMP DEFAULT now(), "updatedBy" character varying(36), "isDeleted" boolean NOT NULL DEFAULT false, "school" character varying(200), "educationLevel" character varying(50), "major" character varying(150), "graduationYear" integer, "languages" character varying(200), "certificates" text, "skills" text, "startYear" integer NOT NULL, "endYear" integer NOT NULL, "gpa" double precision, "employeeId" uuid, CONSTRAINT "PK_29e13ff7f69077fc42445b0c305" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "career_path" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(36) NOT NULL, "updatedAt" TIMESTAMP DEFAULT now(), "updatedBy" character varying(36), "isDeleted" boolean NOT NULL DEFAULT false, "currentPositionId" uuid NOT NULL, "nextPositionId" uuid NOT NULL, "minMonthExperience" integer, CONSTRAINT "PK_0e893f9053f1ea01cd33636b1e2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "part_master_position_master" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(36) NOT NULL, "updatedAt" TIMESTAMP DEFAULT now(), "updatedBy" character varying(36), "isDeleted" boolean NOT NULL DEFAULT false, "partMasterId" uuid NOT NULL, "positionMasterId" uuid NOT NULL, CONSTRAINT "PK_d1dba4bdf4d5d8d729840aa5a14" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "shift_master" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(36) NOT NULL, "updatedAt" TIMESTAMP DEFAULT now(), "updatedBy" character varying(36), "isDeleted" boolean NOT NULL DEFAULT false, "code" character varying NOT NULL, "name" character varying NOT NULL, "startTime" TIME NOT NULL, "endTime" TIME NOT NULL, "companyId" uuid, CONSTRAINT "PK_2d5810d9abc3fcdc5c86b7681c3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "shift" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(36) NOT NULL, "updatedAt" TIMESTAMP DEFAULT now(), "updatedBy" character varying(36), "isDeleted" boolean NOT NULL DEFAULT false, "code" character varying NOT NULL, "name" character varying NOT NULL, "shiftMasterId" uuid NOT NULL, CONSTRAINT "PK_53071a6485a1e9dc75ec3db54b9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "branch_part_master" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(36) NOT NULL, "updatedAt" TIMESTAMP DEFAULT now(), "updatedBy" character varying(36), "isDeleted" boolean NOT NULL DEFAULT false, "branchId" uuid NOT NULL, "partMasterId" uuid NOT NULL, CONSTRAINT "PK_5ab0dd595f23a60cc30853cf54e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "transfer_employee_position" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(36) NOT NULL, "updatedAt" TIMESTAMP DEFAULT now(), "updatedBy" character varying(36), "isDeleted" boolean NOT NULL DEFAULT false, "transferEmployeeDetailId" uuid NOT NULL, "newBranchId" uuid NOT NULL, "newDepartmentId" uuid NOT NULL, "newPositionId" uuid NOT NULL, "newSalary" numeric, "note" text, CONSTRAINT "UQ_272bf393ff237ead169d2154d15" UNIQUE ("transferEmployeeDetailId"), CONSTRAINT "REL_272bf393ff237ead169d2154d1" UNIQUE ("transferEmployeeDetailId"), CONSTRAINT "PK_0dea9d7caf8f1abdbc361fca97f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "transfer_employee_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(36) NOT NULL, "updatedAt" TIMESTAMP DEFAULT now(), "updatedBy" character varying(36), "isDeleted" boolean NOT NULL DEFAULT false, "transferEmployeeId" uuid NOT NULL, "action" character varying NOT NULL, "actorId" character varying, "comment" text, CONSTRAINT "PK_20294c6dddb2f1054884ea06b64" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "transfer_employee" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(36) NOT NULL, "updatedAt" TIMESTAMP DEFAULT now(), "updatedBy" character varying(36), "isDeleted" boolean NOT NULL DEFAULT false, "code" character varying NOT NULL, "name" character varying NOT NULL, "effectiveDate" TIMESTAMP WITH TIME ZONE NOT NULL, "status" character varying NOT NULL DEFAULT 'DRAFT', "type" character varying NOT NULL, CONSTRAINT "UQ_420aaeb48f415685600d236c2c4" UNIQUE ("code"), CONSTRAINT "PK_c865eff862960828d5337bf72c5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "transfer_employee_detail" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(36) NOT NULL, "updatedAt" TIMESTAMP DEFAULT now(), "updatedBy" character varying(36), "isDeleted" boolean NOT NULL DEFAULT false, "transferEmployeeId" uuid NOT NULL, "employeeId" uuid NOT NULL, "oldBranchId" uuid, "oldDepartmentId" uuid, "oldPositionId" uuid, CONSTRAINT "PK_ad5e8d26fd7a11b3d6186940eb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "department_closure" ("id_ancestor" uuid NOT NULL, "id_descendant" uuid NOT NULL, CONSTRAINT "PK_f74940bae8b56b4a236d4cd744e" PRIMARY KEY ("id_ancestor", "id_descendant"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1064ab8229f1b6209dbd90eaed" ON "department_closure" ("id_ancestor") `);
        await queryRunner.query(`CREATE INDEX "IDX_ccad6720dcf2b6705ca99a00d5" ON "department_closure" ("id_descendant") `);
        await queryRunner.query(`ALTER TABLE "part_master" DROP COLUMN "lstPositionMasterId"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "graduationYear"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "educationLevel"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "major"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "school"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "languages"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "certificates"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "skills"`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "timeKeepingStandardId"`);
        await queryRunner.query(`ALTER TABLE "part" ADD "branchId" uuid`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "shiftId" uuid`);
        await queryRunner.query(`ALTER TABLE "department" ADD "parentDepartmentId" uuid`);
        await queryRunner.query(`ALTER TABLE "company" ADD "taxCode" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "company" ADD "phoneNumber" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "company" ADD "email" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "company" ADD "website" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "company" ADD "currency" character varying(20) NOT NULL DEFAULT 'VND'`);
        await queryRunner.query(`ALTER TABLE "company" ADD "logoUrl" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "upload_files" ADD "cvEmployeeId" uuid`);
        await queryRunner.query(`ALTER TABLE "upload_files" ADD "contractEmployeeId" uuid`);
        await queryRunner.query(`ALTER TABLE "upload_files" ADD "companyId" uuid`);
        await queryRunner.query(`ALTER TABLE "upload_files" ADD "employeeCertificateId" uuid`);
        await queryRunner.query(`ALTER TABLE "upload_files" ADD "employeeEducationId" uuid`);
        await queryRunner.query(`ALTER TABLE "upload_files" ADD "transferEmployeeId" uuid`);
        await queryRunner.query(`ALTER TABLE "branch" DROP COLUMN "isHeadquarters"`);
        await queryRunner.query(`ALTER TABLE "branch" ADD "isHeadquarters" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "employee_certificate" ADD CONSTRAINT "FK_9b4dae8cfbae320019f4f96f3f5" FOREIGN KEY ("employeeId") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_education" ADD CONSTRAINT "FK_8e22dbe672750c0db7ab23e153a" FOREIGN KEY ("employeeId") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "career_path" ADD CONSTRAINT "FK_e3d039a9d32b44b4b1c61a3771c" FOREIGN KEY ("currentPositionId") REFERENCES "position_master"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "career_path" ADD CONSTRAINT "FK_224fd24839809e6ca6a35b7fadd" FOREIGN KEY ("nextPositionId") REFERENCES "position_master"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "part_master_position_master" ADD CONSTRAINT "FK_efe09cb960911ece16a4295e166" FOREIGN KEY ("partMasterId") REFERENCES "part_master"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "part_master_position_master" ADD CONSTRAINT "FK_0573dab1c7d64b8588052baba66" FOREIGN KEY ("positionMasterId") REFERENCES "position_master"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "part" ADD CONSTRAINT "FK_3652e8465709aaef820dd7f4e29" FOREIGN KEY ("branchId") REFERENCES "branch"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shift_master" ADD CONSTRAINT "FK_ba48e1a0a682e3d7ea2a59bf8e1" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shift" ADD CONSTRAINT "FK_76be9c684a9d1b8a63025ed0ef4" FOREIGN KEY ("shiftMasterId") REFERENCES "shift_master"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_f788ad0f4d3c5b99056c533fb68" FOREIGN KEY ("shiftId") REFERENCES "shift"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "department" ADD CONSTRAINT "FK_bbe097728367bd569b5db49db90" FOREIGN KEY ("parentDepartmentId") REFERENCES "department"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company" ADD CONSTRAINT "FK_aa8f384a989014b9f826b7fdc5e" FOREIGN KEY ("parentCompanyId") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_part_master" ADD CONSTRAINT "FK_e6d0ffb7b0ce41ff7241e9c26d4" FOREIGN KEY ("branchId") REFERENCES "branch"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_part_master" ADD CONSTRAINT "FK_39a436abff95203d4697139eeb5" FOREIGN KEY ("partMasterId") REFERENCES "part_master"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_position" ADD CONSTRAINT "FK_272bf393ff237ead169d2154d15" FOREIGN KEY ("transferEmployeeDetailId") REFERENCES "transfer_employee_detail"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_position" ADD CONSTRAINT "FK_272f577b782071c0ea1f75befc5" FOREIGN KEY ("newBranchId") REFERENCES "branch"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_position" ADD CONSTRAINT "FK_e3e28832d9497f3108546641551" FOREIGN KEY ("newDepartmentId") REFERENCES "department"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_position" ADD CONSTRAINT "FK_0a052f6e6d58452d18a219707b7" FOREIGN KEY ("newPositionId") REFERENCES "position"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_history" ADD CONSTRAINT "FK_c53b480058c0d4678f5d05c3875" FOREIGN KEY ("transferEmployeeId") REFERENCES "transfer_employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_detail" ADD CONSTRAINT "FK_4b14b634a5824a1680795de5b16" FOREIGN KEY ("transferEmployeeId") REFERENCES "transfer_employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_detail" ADD CONSTRAINT "FK_1d4087512c1fd7497e0ae8b8125" FOREIGN KEY ("employeeId") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_detail" ADD CONSTRAINT "FK_135329ca15788990ed15e3cd13a" FOREIGN KEY ("oldBranchId") REFERENCES "branch"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_detail" ADD CONSTRAINT "FK_4b22d115fb0948b9b03517765b5" FOREIGN KEY ("oldDepartmentId") REFERENCES "department"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_detail" ADD CONSTRAINT "FK_d050fb0822ec7f96791c0946b50" FOREIGN KEY ("oldPositionId") REFERENCES "position"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "upload_files" ADD CONSTRAINT "FK_3ba730bf7246aa1ea74642dc6ee" FOREIGN KEY ("cvEmployeeId") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "upload_files" ADD CONSTRAINT "FK_c004b24e3257bd7af34438faacf" FOREIGN KEY ("contractEmployeeId") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "upload_files" ADD CONSTRAINT "FK_6d0a3888c10fc7037fc000b65f7" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "upload_files" ADD CONSTRAINT "FK_bf1c3bf8b2c43ffac7dd28bcb65" FOREIGN KEY ("employeeCertificateId") REFERENCES "employee_certificate"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "upload_files" ADD CONSTRAINT "FK_837b90d4635d3d03c3877e69d34" FOREIGN KEY ("employeeEducationId") REFERENCES "employee_education"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "upload_files" ADD CONSTRAINT "FK_be0f68157b6c5214ba38a0c526a" FOREIGN KEY ("transferEmployeeId") REFERENCES "transfer_employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "department_closure" ADD CONSTRAINT "FK_1064ab8229f1b6209dbd90eaed3" FOREIGN KEY ("id_ancestor") REFERENCES "department"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "department_closure" ADD CONSTRAINT "FK_ccad6720dcf2b6705ca99a00d5f" FOREIGN KEY ("id_descendant") REFERENCES "department"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "department_closure" DROP CONSTRAINT "FK_ccad6720dcf2b6705ca99a00d5f"`);
        await queryRunner.query(`ALTER TABLE "department_closure" DROP CONSTRAINT "FK_1064ab8229f1b6209dbd90eaed3"`);
        await queryRunner.query(`ALTER TABLE "upload_files" DROP CONSTRAINT "FK_be0f68157b6c5214ba38a0c526a"`);
        await queryRunner.query(`ALTER TABLE "upload_files" DROP CONSTRAINT "FK_837b90d4635d3d03c3877e69d34"`);
        await queryRunner.query(`ALTER TABLE "upload_files" DROP CONSTRAINT "FK_bf1c3bf8b2c43ffac7dd28bcb65"`);
        await queryRunner.query(`ALTER TABLE "upload_files" DROP CONSTRAINT "FK_6d0a3888c10fc7037fc000b65f7"`);
        await queryRunner.query(`ALTER TABLE "upload_files" DROP CONSTRAINT "FK_c004b24e3257bd7af34438faacf"`);
        await queryRunner.query(`ALTER TABLE "upload_files" DROP CONSTRAINT "FK_3ba730bf7246aa1ea74642dc6ee"`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_detail" DROP CONSTRAINT "FK_d050fb0822ec7f96791c0946b50"`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_detail" DROP CONSTRAINT "FK_4b22d115fb0948b9b03517765b5"`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_detail" DROP CONSTRAINT "FK_135329ca15788990ed15e3cd13a"`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_detail" DROP CONSTRAINT "FK_1d4087512c1fd7497e0ae8b8125"`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_detail" DROP CONSTRAINT "FK_4b14b634a5824a1680795de5b16"`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_history" DROP CONSTRAINT "FK_c53b480058c0d4678f5d05c3875"`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_position" DROP CONSTRAINT "FK_0a052f6e6d58452d18a219707b7"`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_position" DROP CONSTRAINT "FK_e3e28832d9497f3108546641551"`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_position" DROP CONSTRAINT "FK_272f577b782071c0ea1f75befc5"`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_position" DROP CONSTRAINT "FK_272bf393ff237ead169d2154d15"`);
        await queryRunner.query(`ALTER TABLE "branch_part_master" DROP CONSTRAINT "FK_39a436abff95203d4697139eeb5"`);
        await queryRunner.query(`ALTER TABLE "branch_part_master" DROP CONSTRAINT "FK_e6d0ffb7b0ce41ff7241e9c26d4"`);
        await queryRunner.query(`ALTER TABLE "company" DROP CONSTRAINT "FK_aa8f384a989014b9f826b7fdc5e"`);
        await queryRunner.query(`ALTER TABLE "department" DROP CONSTRAINT "FK_bbe097728367bd569b5db49db90"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_f788ad0f4d3c5b99056c533fb68"`);
        await queryRunner.query(`ALTER TABLE "shift" DROP CONSTRAINT "FK_76be9c684a9d1b8a63025ed0ef4"`);
        await queryRunner.query(`ALTER TABLE "shift_master" DROP CONSTRAINT "FK_ba48e1a0a682e3d7ea2a59bf8e1"`);
        await queryRunner.query(`ALTER TABLE "part" DROP CONSTRAINT "FK_3652e8465709aaef820dd7f4e29"`);
        await queryRunner.query(`ALTER TABLE "part_master_position_master" DROP CONSTRAINT "FK_0573dab1c7d64b8588052baba66"`);
        await queryRunner.query(`ALTER TABLE "part_master_position_master" DROP CONSTRAINT "FK_efe09cb960911ece16a4295e166"`);
        await queryRunner.query(`ALTER TABLE "career_path" DROP CONSTRAINT "FK_224fd24839809e6ca6a35b7fadd"`);
        await queryRunner.query(`ALTER TABLE "career_path" DROP CONSTRAINT "FK_e3d039a9d32b44b4b1c61a3771c"`);
        await queryRunner.query(`ALTER TABLE "employee_education" DROP CONSTRAINT "FK_8e22dbe672750c0db7ab23e153a"`);
        await queryRunner.query(`ALTER TABLE "employee_certificate" DROP CONSTRAINT "FK_9b4dae8cfbae320019f4f96f3f5"`);
        await queryRunner.query(`ALTER TABLE "branch" DROP COLUMN "isHeadquarters"`);
        await queryRunner.query(`ALTER TABLE "branch" ADD "isHeadquarters" text`);
        await queryRunner.query(`ALTER TABLE "upload_files" DROP COLUMN "transferEmployeeId"`);
        await queryRunner.query(`ALTER TABLE "upload_files" DROP COLUMN "employeeEducationId"`);
        await queryRunner.query(`ALTER TABLE "upload_files" DROP COLUMN "employeeCertificateId"`);
        await queryRunner.query(`ALTER TABLE "upload_files" DROP COLUMN "companyId"`);
        await queryRunner.query(`ALTER TABLE "upload_files" DROP COLUMN "contractEmployeeId"`);
        await queryRunner.query(`ALTER TABLE "upload_files" DROP COLUMN "cvEmployeeId"`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "logoUrl"`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "currency"`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "website"`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "phoneNumber"`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "taxCode"`);
        await queryRunner.query(`ALTER TABLE "department" DROP COLUMN "parentDepartmentId"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "shiftId"`);
        await queryRunner.query(`ALTER TABLE "part" DROP COLUMN "branchId"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "timeKeepingStandardId" uuid`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "skills" text`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "certificates" text`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "languages" character varying(200)`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "school" character varying(200)`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "major" character varying(150)`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "educationLevel" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "graduationYear" integer`);
        await queryRunner.query(`ALTER TABLE "part_master" ADD "lstPositionMasterId" text`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ccad6720dcf2b6705ca99a00d5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1064ab8229f1b6209dbd90eaed"`);
        await queryRunner.query(`DROP TABLE "department_closure"`);
        await queryRunner.query(`DROP TABLE "transfer_employee_detail"`);
        await queryRunner.query(`DROP TABLE "transfer_employee"`);
        await queryRunner.query(`DROP TABLE "transfer_employee_history"`);
        await queryRunner.query(`DROP TABLE "transfer_employee_position"`);
        await queryRunner.query(`DROP TABLE "branch_part_master"`);
        await queryRunner.query(`DROP TABLE "shift"`);
        await queryRunner.query(`DROP TABLE "shift_master"`);
        await queryRunner.query(`DROP TABLE "part_master_position_master"`);
        await queryRunner.query(`DROP TABLE "career_path"`);
        await queryRunner.query(`DROP TABLE "employee_education"`);
        await queryRunner.query(`DROP TABLE "employee_certificate"`);
        await queryRunner.query(`ALTER TABLE "branch" RENAME COLUMN "isHeadquarters" TO "lstPartMasterId"`);
    }

}
