import { MigrationInterface, QueryRunner } from "typeorm";

export class ChangeData1765307836954 implements MigrationInterface {
    name = 'ChangeData1765307836954'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "setting_string" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(36) NOT NULL, "updatedAt" TIMESTAMP DEFAULT now(), "updatedBy" character varying(36), "isDeleted" boolean NOT NULL DEFAULT false, "code" character varying(100) NOT NULL, "name" character varying(250) NOT NULL, "type" character varying(50) NOT NULL DEFAULT 'string', "value" double precision, "valueString" text, CONSTRAINT "PK_cd993a95b69adc4fcb1c4e779c3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "action_log" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(36) NOT NULL, "updatedAt" TIMESTAMP DEFAULT now(), "updatedBy" character varying(36), "isDeleted" boolean NOT NULL DEFAULT false, "createdById" uuid, "createdByName" character varying(250) NOT NULL, "createdNote" character varying(500), "description" text NOT NULL, "dataOld" text, "dataNew" text, "type" character varying NOT NULL, "functionType" character varying(250) NOT NULL, "functionId" uuid, CONSTRAINT "PK_63cffa5d8af90621882f0388359" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "department_type" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(36) NOT NULL, "updatedAt" TIMESTAMP DEFAULT now(), "updatedBy" character varying(36), "isDeleted" boolean NOT NULL DEFAULT false, "code" character varying(50) NOT NULL, "name" character varying(50) NOT NULL, "description" character varying(255), CONSTRAINT "UQ_846a1e6321cb2bac3b212898bff" UNIQUE ("code"), CONSTRAINT "UQ_433ef7e9c79de1eb9ddb01b1d2c" UNIQUE ("name"), CONSTRAINT "PK_d3505563499e91b61bd3e7a613f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "part_master" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(36) NOT NULL, "updatedAt" TIMESTAMP DEFAULT now(), "updatedBy" character varying(36), "isDeleted" boolean NOT NULL DEFAULT false, "code" character varying(50) NOT NULL, "name" character varying(250) NOT NULL, "description" text, "lstPositionMasterId" text, CONSTRAINT "PK_4bbfbce678d8de988e0795bbe26" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "position_master" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(36) NOT NULL, "updatedAt" TIMESTAMP DEFAULT now(), "updatedBy" character varying(36), "isDeleted" boolean NOT NULL DEFAULT false, "code" character varying(50) NOT NULL, "name" character varying(250) NOT NULL, "description" text, "isLimitHoursWorking" boolean DEFAULT false, "limit" character varying(50), "workingHour" integer, "isTimeKeeping" boolean DEFAULT false, "hourWorkingStart" TIMESTAMP, "hourWorkingEnd" TIMESTAMP, "hourSnapShotStart" TIMESTAMP, "hourSnapShotEnd" TIMESTAMP, "minimumWorkingHour" integer, "isSwapPosition" boolean DEFAULT false, "targetChangePositionId" text, "isApprovedWhenHiringCandidate" boolean DEFAULT true, "isHadASecondInterview" boolean DEFAULT false, "isApprovedDayOff" boolean DEFAULT false, CONSTRAINT "PK_0e5be616996c50a27ee25dd5a15" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "position" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(36) NOT NULL, "updatedAt" TIMESTAMP DEFAULT now(), "updatedBy" character varying(36), "isDeleted" boolean NOT NULL DEFAULT false, "code" character varying(50) NOT NULL, "name" character varying(250) NOT NULL, "description" text, "companyId" uuid, "departmentId" uuid, "branchId" uuid, "partId" uuid, "isLimitHoursWorking" boolean DEFAULT false, "limit" character varying(50), "workingHour" integer, "isTimeKeeping" boolean DEFAULT false, "hourWorkingStart" TIMESTAMP, "hourWorkingEnd" TIMESTAMP, "hourSnapShotStart" TIMESTAMP, "hourSnapShotEnd" TIMESTAMP, "minimumWorkingHour" integer, "isSwapPosition" boolean DEFAULT false, "targetChangePositionId" text, "isApprovedWhenHiringCandidate" boolean DEFAULT true, "content" text, "positionMasterId" uuid, CONSTRAINT "PK_b7f483581562b4dc62ae1a5b7e2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "part" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(36) NOT NULL, "updatedAt" TIMESTAMP DEFAULT now(), "updatedBy" character varying(36), "isDeleted" boolean NOT NULL DEFAULT false, "code" character varying(50) NOT NULL, "name" character varying(250) NOT NULL, "description" text, "partMasterId" uuid, "departmentId" uuid, "companyId" uuid, CONSTRAINT "PK_58888debdf048d2dfe459aa59da" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "department" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(36) NOT NULL, "updatedAt" TIMESTAMP DEFAULT now(), "updatedBy" character varying(36), "isDeleted" boolean NOT NULL DEFAULT false, "code" character varying(50) NOT NULL, "name" character varying(250) NOT NULL, "description" text, "limit" integer NOT NULL, "departmentTypeId" uuid, "companyId" uuid, "branchId" uuid, CONSTRAINT "PK_9a2213262c1593bffb581e382f5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "company" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(36) NOT NULL, "updatedAt" TIMESTAMP DEFAULT now(), "updatedBy" character varying(36), "isDeleted" boolean NOT NULL DEFAULT false, "code" character varying(50) NOT NULL, "name" character varying(250) NOT NULL, "description" text, "address" text, "parentCompanyId" uuid, "prefixFemaleCode" integer, "prefixMaleCode" integer, "prefixFullTimeModeCode" character varying(12), "prefixPartTimeModeCode" character varying(12), "timeKeepingStandardId" uuid, CONSTRAINT "PK_056f7854a7afdba7cbd6d45fc20" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "branch" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(36) NOT NULL, "updatedAt" TIMESTAMP DEFAULT now(), "updatedBy" character varying(36), "isDeleted" boolean NOT NULL DEFAULT false, "code" character varying(50) NOT NULL, "name" character varying(250) NOT NULL, "companyId" uuid, "description" character varying(255), "address" text, "ipAddress" character varying(30), "shortName" character varying(250), "lstPartMasterId" text, "type" character varying(50), CONSTRAINT "PK_2e39f426e2faefdaa93c5961976" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "upload_files" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(36) NOT NULL, "updatedAt" TIMESTAMP DEFAULT now(), "updatedBy" character varying(36), "isDeleted" boolean NOT NULL DEFAULT false, "fileUrl" text NOT NULL, "fileName" text NOT NULL, "fileType" character varying(50), "fileSize" bigint, "description" text, "avatarEmployeeId" uuid, "frontIdCardEmployeeId" uuid, "backIdCardEmployeeId" uuid, CONSTRAINT "PK_dae64affe0c302fbf9e0c24d989" PRIMARY KEY ("id")); COMMENT ON COLUMN "upload_files"."fileUrl" IS 'Đường dẫn tệp'; COMMENT ON COLUMN "upload_files"."fileName" IS 'Tên tệp'; COMMENT ON COLUMN "upload_files"."description" IS 'Mô tả tệp'`);
        await queryRunner.query(`CREATE TABLE "employee" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(36) NOT NULL, "updatedAt" TIMESTAMP DEFAULT now(), "updatedBy" character varying(36), "isDeleted" boolean NOT NULL DEFAULT false, "code" character varying(50) NOT NULL, "lastName" character varying(30) NOT NULL, "firstName" character varying(250) NOT NULL, "fullName" character varying(250), "phone" character varying(25) NOT NULL, "secondaryPhone" character varying(25), "email" character varying(250) NOT NULL, "gender" character varying(10) NOT NULL, "birthday" TIMESTAMP WITH TIME ZONE NOT NULL, "nationality" character varying(50) DEFAULT 'Việt Nam', "ethnicity" character varying(50), "religion" character varying(50), "identityCard" character varying(12) NOT NULL, "placeOfIssuance" text NOT NULL, "issuanceDate" TIMESTAMP WITH TIME ZONE NOT NULL, "permanentAddress" text NOT NULL, "nowAddress" character varying(255) NOT NULL, "currentCity" character varying(100) NOT NULL, "currentDistrict" character varying(100) NOT NULL, "currentWard" character varying(100) NOT NULL, "passportNumber" character varying(20), "passportIssueDate" TIMESTAMP WITH TIME ZONE, "passportExpiryDate" TIMESTAMP WITH TIME ZONE, "socialInsuranceNumber" character varying(20), "healthInsuranceNumber" character varying(20), "bankAccountNumber" character varying(50) NOT NULL, "bankName" character varying(100) NOT NULL, "bankBranch" character varying(150) NOT NULL, "bankAccountHolder" character varying(250) NOT NULL, "taxCode" character varying(20), "companyEmail" character varying(250), "branchId" uuid, "departmentId" uuid, "partId" uuid, "positionMasterId" uuid, "positionId" uuid, "level" character varying(50), "workingMode" character varying(50) NOT NULL, "contractType" character varying(50), "dateStartProbation" TIMESTAMP WITH TIME ZONE, "dateEndProbation" TIMESTAMP WITH TIME ZONE, "dateStartOfficial" TIMESTAMP WITH TIME ZONE, "contractSignDate" TIMESTAMP WITH TIME ZONE, "contractEndDate" TIMESTAMP WITH TIME ZONE, "workingDuration" integer, "educationLevel" character varying(50), "major" character varying(150), "school" character varying(200), "graduationYear" integer, "languages" character varying(200), "certificates" text, "skills" text, "emergencyContactName" character varying(250), "emergencyContactRelation" character varying(100), "emergencyContactPhone" character varying(25), "emergencyContactAddress" text, "status" character varying(36), "resignationDate" TIMESTAMP WITH TIME ZONE, "resignationReason" text, "description" text, "internalNote" text, "hasSystemAccess" boolean DEFAULT true, "receiveNotification" boolean DEFAULT true, "managerId" uuid, "companyId" uuid, CONSTRAINT "UQ_348a4a9894eef0760bfe0a26328" UNIQUE ("code"), CONSTRAINT "PK_3c2bc72f03fd5abbbc5ac169498" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notification_recipients" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(36) NOT NULL, "updatedAt" TIMESTAMP DEFAULT now(), "updatedBy" character varying(36), "isDeleted" boolean NOT NULL DEFAULT false, "notificationId" uuid NOT NULL, "userId" uuid NOT NULL, "isRead" boolean NOT NULL DEFAULT false, "readAt" TIMESTAMP, CONSTRAINT "PK_bd5b25c456987261a38c762b223" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(36) NOT NULL, "updatedAt" TIMESTAMP DEFAULT now(), "updatedBy" character varying(36), "isDeleted" boolean NOT NULL DEFAULT false, "title" character varying(500) NOT NULL, "content" text NOT NULL, "type" character varying(50), "priority" character varying(20) NOT NULL DEFAULT 'normal', "senderId" uuid, "targetAudience" character varying(100), "classId" uuid, "publishDate" TIMESTAMP NOT NULL DEFAULT now(), "expiryDate" TIMESTAMP, "status" character varying(20) NOT NULL DEFAULT 'draft', "attachments" text, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(36) NOT NULL, "updatedAt" TIMESTAMP DEFAULT now(), "updatedBy" character varying(36), "isDeleted" boolean NOT NULL DEFAULT false, "roleId" uuid NOT NULL, "permissionId" uuid NOT NULL, "scope" character varying(20) NOT NULL, CONSTRAINT "PK_84059017c90bfcb701b8fa42297" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(36) NOT NULL, "updatedAt" TIMESTAMP DEFAULT now(), "updatedBy" character varying(36), "isDeleted" boolean NOT NULL DEFAULT false, "name" character varying(255) NOT NULL, "code" character varying(100) NOT NULL, "module" character varying(100), "description" text, CONSTRAINT "UQ_8dad765629e83229da6feda1c1d" UNIQUE ("code"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8dad765629e83229da6feda1c1" ON "permissions" ("code") `);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(36) NOT NULL, "updatedAt" TIMESTAMP DEFAULT now(), "updatedBy" character varying(36), "isDeleted" boolean NOT NULL DEFAULT false, "name" character varying(100) NOT NULL, "code" character varying(50), "description" text, "isSystem" boolean NOT NULL DEFAULT false, "parentId" uuid, CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "UQ_f6d54f95c31b73fb1bdd8e91d0c" UNIQUE ("code"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(36) NOT NULL, "updatedAt" TIMESTAMP DEFAULT now(), "updatedBy" character varying(36), "isDeleted" boolean NOT NULL DEFAULT false, "userId" uuid NOT NULL, "roleId" uuid NOT NULL, "assignedDate" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::date, "assignedById" uuid, CONSTRAINT "PK_8acd5cf26ebd158416f477de799" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(36) NOT NULL, "updatedAt" TIMESTAMP DEFAULT now(), "updatedBy" character varying(36), "isDeleted" boolean NOT NULL DEFAULT false, "username" character varying(100) NOT NULL, "password" character varying(255) NOT NULL, "email" character varying(255) NOT NULL, "employeeId" uuid, "isActive" boolean NOT NULL DEFAULT true, "isAdmin" boolean NOT NULL DEFAULT false, "refreshToken" text, "lastLogin" TIMESTAMP, CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "REL_a7191f881489123fab6c8e5273" UNIQUE ("employeeId"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "position" ADD CONSTRAINT "FK_4795972601ff1d8b498ebc3d031" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "position" ADD CONSTRAINT "FK_265308a419e87c0f9eb399099da" FOREIGN KEY ("departmentId") REFERENCES "department"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "position" ADD CONSTRAINT "FK_2511fdfffa942a5648ef8c82868" FOREIGN KEY ("branchId") REFERENCES "branch"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "position" ADD CONSTRAINT "FK_3066621b6e86359a773ee35fa4f" FOREIGN KEY ("partId") REFERENCES "part"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "position" ADD CONSTRAINT "FK_3832173b4fb430e33d9050c6bce" FOREIGN KEY ("positionMasterId") REFERENCES "position_master"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "part" ADD CONSTRAINT "FK_9abe7e35fa0c0c16f142af049f5" FOREIGN KEY ("partMasterId") REFERENCES "part_master"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "part" ADD CONSTRAINT "FK_9734b72ea1fb0688d79cd5b0016" FOREIGN KEY ("departmentId") REFERENCES "department"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "part" ADD CONSTRAINT "FK_54b146ebe4e9e9e8bf8cfd55c5c" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "department" ADD CONSTRAINT "FK_117b2b6099c401581bf8c0399b4" FOREIGN KEY ("departmentTypeId") REFERENCES "department_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "department" ADD CONSTRAINT "FK_1c9f0159b4ae69008bd356bb1ce" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "department" ADD CONSTRAINT "FK_a44bcea55f11d1502fc11e39fe7" FOREIGN KEY ("branchId") REFERENCES "branch"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch" ADD CONSTRAINT "FK_d916e8de3e93fdf6bd13c734237" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "upload_files" ADD CONSTRAINT "FK_65a25304c6f76f0dfe3960b1f02" FOREIGN KEY ("avatarEmployeeId") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "upload_files" ADD CONSTRAINT "FK_25b39997bacdc96d071d943f163" FOREIGN KEY ("frontIdCardEmployeeId") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "upload_files" ADD CONSTRAINT "FK_769d99bd544648ac44b1176ede4" FOREIGN KEY ("backIdCardEmployeeId") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_c36b6dc182259c56ee8c1cfecb3" FOREIGN KEY ("branchId") REFERENCES "branch"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_9ad20e4029f9458b6eed0b0c454" FOREIGN KEY ("departmentId") REFERENCES "department"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_41f32656086e8795d0665a024ba" FOREIGN KEY ("partId") REFERENCES "part"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_217188c2b6f643fb5fdf501c041" FOREIGN KEY ("positionMasterId") REFERENCES "position_master"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_aff396af6e595420a64943f4c26" FOREIGN KEY ("positionId") REFERENCES "position"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_f4a920dfa304e096fad40e8c4a0" FOREIGN KEY ("managerId") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_26c3d513e0832e5abbbdd3d2a88" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_recipients" ADD CONSTRAINT "FK_234adaa36f97dd1b2bd3a22d65b" FOREIGN KEY ("notificationId") REFERENCES "notifications"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_recipients" ADD CONSTRAINT "FK_452385a8220b8053ab65317ffa6" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_ddb7981cf939fe620179bfea33a" FOREIGN KEY ("senderId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_b4599f8b8f548d35850afa2d12c" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_06792d0c62ce6b0203c03643cdd" FOREIGN KEY ("permissionId") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_472b25323af01488f1f66a06b67" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_86033897c009fcca8b6505d6be2" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_2c43c3d51c42929dd1684d049cf" FOREIGN KEY ("assignedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a7191f881489123fab6c8e52738" FOREIGN KEY ("employeeId") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a7191f881489123fab6c8e52738"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_2c43c3d51c42929dd1684d049cf"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_86033897c009fcca8b6505d6be2"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_472b25323af01488f1f66a06b67"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_06792d0c62ce6b0203c03643cdd"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_b4599f8b8f548d35850afa2d12c"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_ddb7981cf939fe620179bfea33a"`);
        await queryRunner.query(`ALTER TABLE "notification_recipients" DROP CONSTRAINT "FK_452385a8220b8053ab65317ffa6"`);
        await queryRunner.query(`ALTER TABLE "notification_recipients" DROP CONSTRAINT "FK_234adaa36f97dd1b2bd3a22d65b"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_26c3d513e0832e5abbbdd3d2a88"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_f4a920dfa304e096fad40e8c4a0"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_aff396af6e595420a64943f4c26"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_217188c2b6f643fb5fdf501c041"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_41f32656086e8795d0665a024ba"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_9ad20e4029f9458b6eed0b0c454"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_c36b6dc182259c56ee8c1cfecb3"`);
        await queryRunner.query(`ALTER TABLE "upload_files" DROP CONSTRAINT "FK_769d99bd544648ac44b1176ede4"`);
        await queryRunner.query(`ALTER TABLE "upload_files" DROP CONSTRAINT "FK_25b39997bacdc96d071d943f163"`);
        await queryRunner.query(`ALTER TABLE "upload_files" DROP CONSTRAINT "FK_65a25304c6f76f0dfe3960b1f02"`);
        await queryRunner.query(`ALTER TABLE "branch" DROP CONSTRAINT "FK_d916e8de3e93fdf6bd13c734237"`);
        await queryRunner.query(`ALTER TABLE "department" DROP CONSTRAINT "FK_a44bcea55f11d1502fc11e39fe7"`);
        await queryRunner.query(`ALTER TABLE "department" DROP CONSTRAINT "FK_1c9f0159b4ae69008bd356bb1ce"`);
        await queryRunner.query(`ALTER TABLE "department" DROP CONSTRAINT "FK_117b2b6099c401581bf8c0399b4"`);
        await queryRunner.query(`ALTER TABLE "part" DROP CONSTRAINT "FK_54b146ebe4e9e9e8bf8cfd55c5c"`);
        await queryRunner.query(`ALTER TABLE "part" DROP CONSTRAINT "FK_9734b72ea1fb0688d79cd5b0016"`);
        await queryRunner.query(`ALTER TABLE "part" DROP CONSTRAINT "FK_9abe7e35fa0c0c16f142af049f5"`);
        await queryRunner.query(`ALTER TABLE "position" DROP CONSTRAINT "FK_3832173b4fb430e33d9050c6bce"`);
        await queryRunner.query(`ALTER TABLE "position" DROP CONSTRAINT "FK_3066621b6e86359a773ee35fa4f"`);
        await queryRunner.query(`ALTER TABLE "position" DROP CONSTRAINT "FK_2511fdfffa942a5648ef8c82868"`);
        await queryRunner.query(`ALTER TABLE "position" DROP CONSTRAINT "FK_265308a419e87c0f9eb399099da"`);
        await queryRunner.query(`ALTER TABLE "position" DROP CONSTRAINT "FK_4795972601ff1d8b498ebc3d031"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8dad765629e83229da6feda1c1"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TABLE "notification_recipients"`);
        await queryRunner.query(`DROP TABLE "employee"`);
        await queryRunner.query(`DROP TABLE "upload_files"`);
        await queryRunner.query(`DROP TABLE "branch"`);
        await queryRunner.query(`DROP TABLE "company"`);
        await queryRunner.query(`DROP TABLE "department"`);
        await queryRunner.query(`DROP TABLE "part"`);
        await queryRunner.query(`DROP TABLE "position"`);
        await queryRunner.query(`DROP TABLE "position_master"`);
        await queryRunner.query(`DROP TABLE "part_master"`);
        await queryRunner.query(`DROP TABLE "department_type"`);
        await queryRunner.query(`DROP TABLE "action_log"`);
        await queryRunner.query(`DROP TABLE "setting_string"`);
    }

}
