import { MigrationInterface, QueryRunner } from "typeorm";

export class FixDb1766590633586 implements MigrationInterface {
    name = 'FixDb1766590633586'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "upload_files" DROP CONSTRAINT "FK_6d0a3888c10fc7037fc000b65f7"`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "prefixFemaleCode"`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "prefixMaleCode"`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "prefixFullTimeModeCode"`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "prefixPartTimeModeCode"`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "currency"`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "logoUrl"`);
        await queryRunner.query(`ALTER TABLE "upload_files" DROP COLUMN "companyId"`);
        await queryRunner.query(`ALTER TABLE "position" ADD "status" character varying(20) NOT NULL DEFAULT 'ACTIVE'`);
        await queryRunner.query(`ALTER TABLE "position_master" ADD "status" character varying(20) NOT NULL DEFAULT 'ACTIVE'`);
        await queryRunner.query(`ALTER TABLE "part_master" ADD "status" character varying(20) NOT NULL DEFAULT 'ACTIVE'`);
        await queryRunner.query(`ALTER TABLE "part" ADD "status" character varying(20) NOT NULL DEFAULT 'ACTIVE'`);
        await queryRunner.query(`ALTER TABLE "shift_master" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "shift_master" ADD "status" character varying(20) NOT NULL DEFAULT 'ACTIVE'`);
        await queryRunner.query(`ALTER TABLE "shift" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "shift" ADD "startDate" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "shift" ADD "endDate" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "shift" ADD "status" character varying(20) NOT NULL DEFAULT 'ACTIVE'`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "maritalStatus" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "numberOfDependents" integer DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "probationStatus" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "joinDate" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "department" ADD "status" character varying(20) NOT NULL DEFAULT 'ACTIVE'`);
        await queryRunner.query(`ALTER TABLE "company" ADD "status" character varying(20) NOT NULL DEFAULT 'ACTIVE'`);
        await queryRunner.query(`ALTER TABLE "company" ADD "foundedDate" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "company" ADD "legalRepresentative" character varying(250)`);
        await queryRunner.query(`ALTER TABLE "branch" ADD "phoneNumber" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "branch" ADD "email" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "branch" ADD "status" character varying(20) NOT NULL DEFAULT 'ACTIVE'`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_position" ADD "newCompanyId" uuid`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_position" ADD "newPartId" uuid`);
        await queryRunner.query(`ALTER TABLE "transfer_employee" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "transfer_employee" ADD "note" text`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_detail" ADD "oldCompanyId" uuid`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_detail" ADD "oldPartId" uuid`);
        await queryRunner.query(`ALTER TABLE "upload_files" ADD "logoCompanyId" uuid`);
        await queryRunner.query(`ALTER TABLE "upload_files" ADD "documentCompanyId" uuid`);
        await queryRunner.query(`ALTER TABLE "employee_certificate" DROP CONSTRAINT "FK_9b4dae8cfbae320019f4f96f3f5"`);
        await queryRunner.query(`ALTER TABLE "employee_certificate" ALTER COLUMN "employeeId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee_education" DROP CONSTRAINT "FK_8e22dbe672750c0db7ab23e153a"`);
        await queryRunner.query(`ALTER TABLE "employee_education" ALTER COLUMN "employeeId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee_education" ALTER COLUMN "startYear" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee_education" ALTER COLUMN "endYear" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "position" DROP COLUMN "hourWorkingStart"`);
        await queryRunner.query(`ALTER TABLE "position" ADD "hourWorkingStart" TIME`);
        await queryRunner.query(`ALTER TABLE "position" DROP COLUMN "hourWorkingEnd"`);
        await queryRunner.query(`ALTER TABLE "position" ADD "hourWorkingEnd" TIME`);
        await queryRunner.query(`ALTER TABLE "position" DROP COLUMN "hourSnapShotStart"`);
        await queryRunner.query(`ALTER TABLE "position" ADD "hourSnapShotStart" TIME`);
        await queryRunner.query(`ALTER TABLE "position" DROP COLUMN "hourSnapShotEnd"`);
        await queryRunner.query(`ALTER TABLE "position" ADD "hourSnapShotEnd" TIME`);
        await queryRunner.query(`ALTER TABLE "position_master" DROP COLUMN "hourWorkingStart"`);
        await queryRunner.query(`ALTER TABLE "position_master" ADD "hourWorkingStart" TIME`);
        await queryRunner.query(`ALTER TABLE "position_master" DROP COLUMN "hourWorkingEnd"`);
        await queryRunner.query(`ALTER TABLE "position_master" ADD "hourWorkingEnd" TIME`);
        await queryRunner.query(`ALTER TABLE "position_master" DROP COLUMN "hourSnapShotStart"`);
        await queryRunner.query(`ALTER TABLE "position_master" ADD "hourSnapShotStart" TIME`);
        await queryRunner.query(`ALTER TABLE "position_master" DROP COLUMN "hourSnapShotEnd"`);
        await queryRunner.query(`ALTER TABLE "position_master" ADD "hourSnapShotEnd" TIME`);
        await queryRunner.query(`ALTER TABLE "shift_master" DROP CONSTRAINT "FK_ba48e1a0a682e3d7ea2a59bf8e1"`);
        await queryRunner.query(`ALTER TABLE "shift_master" ALTER COLUMN "companyId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_c36b6dc182259c56ee8c1cfecb3"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_9ad20e4029f9458b6eed0b0c454"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_26c3d513e0832e5abbbdd3d2a88"`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "UQ_817d1d427138772d47eca048855" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "UQ_bd17ff525a614ed1e83b180779b" UNIQUE ("identityCard")`);
        await queryRunner.query(`ALTER TABLE "employee" ALTER COLUMN "branchId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee" ALTER COLUMN "departmentId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee" ALTER COLUMN "companyId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "department" ALTER COLUMN "limit" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_position" DROP CONSTRAINT "FK_272f577b782071c0ea1f75befc5"`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_position" DROP CONSTRAINT "FK_e3e28832d9497f3108546641551"`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_position" DROP CONSTRAINT "FK_0a052f6e6d58452d18a219707b7"`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_position" ALTER COLUMN "newBranchId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_position" ALTER COLUMN "newDepartmentId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_position" ALTER COLUMN "newPositionId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_position" ALTER COLUMN "newSalary" TYPE numeric(15,2)`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_history" DROP COLUMN "action"`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_history" ADD "action" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_history" DROP COLUMN "actorId"`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_history" ADD "actorId" uuid`);
        await queryRunner.query(`ALTER TABLE "employee_certificate" ADD CONSTRAINT "FK_9b4dae8cfbae320019f4f96f3f5" FOREIGN KEY ("employeeId") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_education" ADD CONSTRAINT "FK_8e22dbe672750c0db7ab23e153a" FOREIGN KEY ("employeeId") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shift_master" ADD CONSTRAINT "FK_ba48e1a0a682e3d7ea2a59bf8e1" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_c36b6dc182259c56ee8c1cfecb3" FOREIGN KEY ("branchId") REFERENCES "branch"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_9ad20e4029f9458b6eed0b0c454" FOREIGN KEY ("departmentId") REFERENCES "department"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_26c3d513e0832e5abbbdd3d2a88" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_position" ADD CONSTRAINT "FK_272f577b782071c0ea1f75befc5" FOREIGN KEY ("newBranchId") REFERENCES "branch"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_position" ADD CONSTRAINT "FK_e3e28832d9497f3108546641551" FOREIGN KEY ("newDepartmentId") REFERENCES "department"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_position" ADD CONSTRAINT "FK_0a052f6e6d58452d18a219707b7" FOREIGN KEY ("newPositionId") REFERENCES "position"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "upload_files" ADD CONSTRAINT "FK_d34f8122f32ce3e59dcde963b41" FOREIGN KEY ("logoCompanyId") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "upload_files" ADD CONSTRAINT "FK_e9033373ffebbb1fea4e618986c" FOREIGN KEY ("documentCompanyId") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "upload_files" DROP CONSTRAINT "FK_e9033373ffebbb1fea4e618986c"`);
        await queryRunner.query(`ALTER TABLE "upload_files" DROP CONSTRAINT "FK_d34f8122f32ce3e59dcde963b41"`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_position" DROP CONSTRAINT "FK_0a052f6e6d58452d18a219707b7"`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_position" DROP CONSTRAINT "FK_e3e28832d9497f3108546641551"`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_position" DROP CONSTRAINT "FK_272f577b782071c0ea1f75befc5"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_26c3d513e0832e5abbbdd3d2a88"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_9ad20e4029f9458b6eed0b0c454"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_c36b6dc182259c56ee8c1cfecb3"`);
        await queryRunner.query(`ALTER TABLE "shift_master" DROP CONSTRAINT "FK_ba48e1a0a682e3d7ea2a59bf8e1"`);
        await queryRunner.query(`ALTER TABLE "employee_education" DROP CONSTRAINT "FK_8e22dbe672750c0db7ab23e153a"`);
        await queryRunner.query(`ALTER TABLE "employee_certificate" DROP CONSTRAINT "FK_9b4dae8cfbae320019f4f96f3f5"`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_history" DROP COLUMN "actorId"`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_history" ADD "actorId" character varying`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_history" DROP COLUMN "action"`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_history" ADD "action" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_position" ALTER COLUMN "newSalary" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_position" ALTER COLUMN "newPositionId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_position" ALTER COLUMN "newDepartmentId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_position" ALTER COLUMN "newBranchId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_position" ADD CONSTRAINT "FK_0a052f6e6d58452d18a219707b7" FOREIGN KEY ("newPositionId") REFERENCES "position"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_position" ADD CONSTRAINT "FK_e3e28832d9497f3108546641551" FOREIGN KEY ("newDepartmentId") REFERENCES "department"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_position" ADD CONSTRAINT "FK_272f577b782071c0ea1f75befc5" FOREIGN KEY ("newBranchId") REFERENCES "branch"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "department" ALTER COLUMN "limit" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee" ALTER COLUMN "companyId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee" ALTER COLUMN "departmentId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee" ALTER COLUMN "branchId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "UQ_bd17ff525a614ed1e83b180779b"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "UQ_817d1d427138772d47eca048855"`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_26c3d513e0832e5abbbdd3d2a88" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_9ad20e4029f9458b6eed0b0c454" FOREIGN KEY ("departmentId") REFERENCES "department"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_c36b6dc182259c56ee8c1cfecb3" FOREIGN KEY ("branchId") REFERENCES "branch"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shift_master" ALTER COLUMN "companyId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "shift_master" ADD CONSTRAINT "FK_ba48e1a0a682e3d7ea2a59bf8e1" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "position_master" DROP COLUMN "hourSnapShotEnd"`);
        await queryRunner.query(`ALTER TABLE "position_master" ADD "hourSnapShotEnd" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "position_master" DROP COLUMN "hourSnapShotStart"`);
        await queryRunner.query(`ALTER TABLE "position_master" ADD "hourSnapShotStart" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "position_master" DROP COLUMN "hourWorkingEnd"`);
        await queryRunner.query(`ALTER TABLE "position_master" ADD "hourWorkingEnd" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "position_master" DROP COLUMN "hourWorkingStart"`);
        await queryRunner.query(`ALTER TABLE "position_master" ADD "hourWorkingStart" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "position" DROP COLUMN "hourSnapShotEnd"`);
        await queryRunner.query(`ALTER TABLE "position" ADD "hourSnapShotEnd" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "position" DROP COLUMN "hourSnapShotStart"`);
        await queryRunner.query(`ALTER TABLE "position" ADD "hourSnapShotStart" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "position" DROP COLUMN "hourWorkingEnd"`);
        await queryRunner.query(`ALTER TABLE "position" ADD "hourWorkingEnd" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "position" DROP COLUMN "hourWorkingStart"`);
        await queryRunner.query(`ALTER TABLE "position" ADD "hourWorkingStart" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "employee_education" ALTER COLUMN "endYear" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee_education" ALTER COLUMN "startYear" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee_education" ALTER COLUMN "employeeId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee_education" ADD CONSTRAINT "FK_8e22dbe672750c0db7ab23e153a" FOREIGN KEY ("employeeId") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_certificate" ALTER COLUMN "employeeId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee_certificate" ADD CONSTRAINT "FK_9b4dae8cfbae320019f4f96f3f5" FOREIGN KEY ("employeeId") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "upload_files" DROP COLUMN "documentCompanyId"`);
        await queryRunner.query(`ALTER TABLE "upload_files" DROP COLUMN "logoCompanyId"`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_detail" DROP COLUMN "oldPartId"`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_detail" DROP COLUMN "oldCompanyId"`);
        await queryRunner.query(`ALTER TABLE "transfer_employee" DROP COLUMN "note"`);
        await queryRunner.query(`ALTER TABLE "transfer_employee" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_position" DROP COLUMN "newPartId"`);
        await queryRunner.query(`ALTER TABLE "transfer_employee_position" DROP COLUMN "newCompanyId"`);
        await queryRunner.query(`ALTER TABLE "branch" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "branch" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "branch" DROP COLUMN "phoneNumber"`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "legalRepresentative"`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "foundedDate"`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "department" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "joinDate"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "probationStatus"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "numberOfDependents"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "maritalStatus"`);
        await queryRunner.query(`ALTER TABLE "shift" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "shift" DROP COLUMN "endDate"`);
        await queryRunner.query(`ALTER TABLE "shift" DROP COLUMN "startDate"`);
        await queryRunner.query(`ALTER TABLE "shift" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "shift_master" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "shift_master" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "part" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "part_master" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "position_master" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "position" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "upload_files" ADD "companyId" uuid`);
        await queryRunner.query(`ALTER TABLE "company" ADD "logoUrl" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "company" ADD "currency" character varying(20) NOT NULL DEFAULT 'VND'`);
        await queryRunner.query(`ALTER TABLE "company" ADD "prefixPartTimeModeCode" character varying(12)`);
        await queryRunner.query(`ALTER TABLE "company" ADD "prefixFullTimeModeCode" character varying(12)`);
        await queryRunner.query(`ALTER TABLE "company" ADD "prefixMaleCode" integer`);
        await queryRunner.query(`ALTER TABLE "company" ADD "prefixFemaleCode" integer`);
        await queryRunner.query(`ALTER TABLE "upload_files" ADD CONSTRAINT "FK_6d0a3888c10fc7037fc000b65f7" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
